### PR TITLE
Added elite college admissions qmd file and data

### PR DESCRIPTION
**Pull request by zhiyujguo**
Due to FERPA restrictions and some of the modeling techniques/assumptions Chetty et al. used, the dataset only contains college-level information for 13+1 income bins. I can't really think of a lot of regression questions but there are definitely interesting EDA/data visualization tasks and maybe ANOVA tests we can do.

### CODE REVIEW

**Comment by capnrefsmmat** [comment]
Thanks, I've started reviewing this and making some edits.

Question: Do you have a good intuitive explanation of what some of the variables mean? For instance, I don't know what a "Test-score-reweighted relative application rate" is. I gather from their codebook that they're adjusting for test scores and for the fact that not all students submit test scores, but I'm not sure how best to explain this to readers. Are there examples or extra explanation we could provide in the table?

**Comment by zhiyujguo** [comment]
Sorry for replying so late, I keep forgetting about this. Basically in the paper, they said, "To obtain a single summary measure of how attendance rates vary with parental income controlling for SAT scores, we average these score-specific series together, putting greater weight on scores that are represented more frequently in the current distribution of Ivy-Plus attendees. More precisely, we take a weighted average of attendance rates by test score in each parental income bin, weighting by the distribution of test scores of students who attend each Ivy-Plus college. We then combine these measures for each of the 12 Ivy-Plus colleges into a single overall mean by taking an enrollment-weighted mean across the 12 colleges and dividing by the overall mean of the result series to obtain measures of relative Ivy-Plus attendance rates by parental income controlling for test scores." So there is a part of adjusting based on the submission of scores as you mentioned (I'm not 100% sure how that's done honestly), but the main adjustments are based on the idea of capturing the variability of parental income level in attendance rate, controlling for SAT scores (with respect to the college/college band). So for example, for Harvard that might mean more weight is placed on students with a 1510-1600 SAT score. I'm not sure if there's a better way to phrase it.

**Comment by capnrefsmmat** [comment]
Thanks, I'm editing that into the data description.

**Comment by capnrefsmmat** [comment]
Finished editing and merged it manually: <https://cmustatistics.github.io/data-repository/social/elite-college-admissions.html>

Thanks for contributing this one -- it should be very interesting. Later we might consider adding some of Opportunity Insights' other datasets, like their mobility report cards.

**Pull request closed without merging**
